language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build

jobs:
  include:
    - stage: lint
      rust: nightly
      install:
        - rustup component add clippy-preview
        - rustup component add rustfmt-preview
      script:
        - cargo clippy -- --deny clippy::all
        - cargo fmt --all -- --check

    - stage: deploy
      branches:
        only:
          - master
      if: tag IS present AND fork = false
      rust: stable
      script:
        - set -e
        - cargo build --release
        - mv target/release/human target/release/human-x86_64-unknown-linux-gnu
        - strip -s target/release/human-x86_64-unknown-linux-gnu
      deploy: &releases
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "target/release/human-x86_64-unknown-linux-gnu"
        skip_cleanup: true
        on:
          tags: true
