[package]
name = "human"
version = "1.0.0"
authors = ["Jan Baudisch <dev@baudisch.xyz>"]
description = "Converts a numeric litaral into an humand-readable format."

[dependencies]
text_io = "0.1.7"

[profile.release]
lto = true
codegen-units = 1
